# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 05:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2016, 5, 19, 5, 20, 28, 641578, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2016, 5, 19, 5, 20, 28, 641659, tzinfo=utc))),
                ('name', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
