# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 05:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todoist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 19, 5, 44, 14, 503785, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 19, 5, 44, 0, 262291, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 19, 5, 44, 0, 262398, tzinfo=utc)),
        ),
    ]
