# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 06:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todoist', '0002_auto_20160519_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 19, 6, 40, 31, 662849, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 19, 6, 40, 31, 662933, tzinfo=utc)),
        ),
    ]
